#!/bin/bash
export ENV=${ENV:-DEVELOPMENT}
export SERVICE_NAME=${SERVICE_NAME:-tilde_app}
export SERVICE_PORT=${SERVICE_PORT:-8000}
export DATABASE_USERNAME=${DATABASE_USERNAME:-tilde_username}
export DATABASE_PASSWORD=${DATABASE_PASSWORD:-tilde_password}
export DATABASE_NAME=${DATABASE_NAME:-tilde_database}
export DATABASE_PORT=${DATABASE_PORT:-5432}
