#!/bin/bash
# Add environment variables from host environment or use value from `Dockerfile`
export SERVICE_NAME=${ENV_SERVICE_NAME}:-${DEFAULT_SERVICE_NAME}
export SERVICE_PORT=${ENV_SERVICE_PORT}:-${DEFAULT_SERVICE_PORT}
export DATABASE_USERNAME=${ENV_DATABASE_USERNAME}:-${DEFAULT_DATABASE_USERNAME}
export DATABASE_PASSWORD=${ENV_DATABASE_PASSWORD}:-${DEFAULT_DATABASE_PASSWORD}
export DATABASE_NAME=${ENV_DATABASE_NAME}:-${DEFAULT_DATABASE_NAME}
export DATABASE_PORT=${ENV_DATABASE_PORT}:-${DEFAULT_DATABASE_PORT}